FROM nginx:1.13.9
MAINTAINER 15228351298@163.COM
COPY /html /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx/nginx.conf

#还可以通过卷挂载 
#docker run container -v /etc/nginx/nginx.conf:etc/nginx/nginx.conf:ro 

